# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      – ‘dbscript/**’

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Use Python 3.10.x
        run: echo Hello, world!
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'
        
        name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{secrets.SF_WAREHOUSE}}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build $SF_ACCOUNT,
          echo test, and deploy your project.
          echo “GITHUB WORKSPACE $GITHUB_WORKSPACE”
          python --version
          echo “Step 1: Initializing Schemachange”
          pip install schemachange
          
          
          echo “Step 2: Running Schemachange”
          schemachange -f $GITHUB_WORKSPACE/dbscript -a $SF_ACCOUNT -u $SF_USERNAME -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE  -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY –create-change-history-table
